### ISSUE TITLE
Clean up RxAndroid dependency

### ISSUE THREAD

**Issue by benhylau** [groundupworks/wings#26]
This needs some cleaning up:

```
     +--- com.groundupworks.wings:wings-gcp:1.0.2
     |    +--- com.netflix.rxjava:rxjava-android:0.20.6
     |    |    \--- com.netflix.rxjava:rxjava-core:0.20.6
     |    +--- com.groundupworks.android:google-auth:1.0.3
     |    |    +--- io.reactivex:rxjava:1.0.2
     |    |    +--- io.reactivex:rxandroid:0.23.0
     |    |    |    \--- io.reactivex:rxjava:1.0.0-rc.9 -> 1.0.2
```

Otherwise we get this:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lrx/android/concurrency/AndroidSchedulers;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
```

For now this fix will do:

```
    compile("com.groundupworks.wings:wings-gcp:$wingsVersion") {
        exclude group: 'com.netflix.rxjava', module: 'rxjava-android'
    }
```

**Comment by benhylau** [comment]
Fixed in GCP module.
